apiVersion: batch/v1
kind: Job
metadata:
  name: cpfs-utils
  namespace: default
spec:
  template:
    spec:
      serviceAccountName: cpfs-utils-sa
      containers:
      - name: cpfs-utils
        image: quay.io/wire/alpine-git:latest
        imagePullPolicy: Always
        command: 
        - /bin/sh
        - -c
        - |
          echo "Downloading convert_to_multi_instance.sh from repo and running it..."
          git clone https://github.com/IBM/ibm-common-service-operator.git
          cd ibm-common-service-operator
          git rev-parse HEAD
          sleep 60
          git rev-parse HEAD
      restartPolicy: Never
      backOffLimit: 2
